version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3001:3001
    command: /bin/sh -c "bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./:/app:cached
      - gem_data:/usr/local/bundle
    stdin_open: true
    tty: true
volumes:
  gem_data: